"""AWEC professional desktop window.
All visible labels are translated at runtime; changing language refreshes the whole UI.
"""
from __future__ import annotations
from pathlib import Path
from PySide6.QtCore import QTimer, Qt
from PySide6.QtWidgets import (QMainWindow,QWidget,QVBoxLayout,QHBoxLayout,QGridLayout,QLabel,
    QPushButton,QLineEdit,QCheckBox,QSpinBox,QDoubleSpinBox,QComboBox,QListWidget,QProgressBar,
    QStackedWidget,QGroupBox,QFileDialog,QTextEdit,QFrame,QFormLayout,QMessageBox)
from .config_schema import AWECConfig

BASE = {
'en': {'title':'AWEC Desktop','dashboard':'Dashboard','crawler':'Crawler','storage':'Storage','languages':'Languages','settings':'Settings','running':'AWEC Running','stopped':'AWEC Stopped','start':'Start','pause':'Pause','stop':'Stop','resume':'Resume','add':'Add','remove':'Remove','import':'Import','browse':'Browse','save':'Save','apply':'Apply','seed':'Seed URLs','follow':'Follow links','sub':'Follow subdomains','external':'Follow external domains','files':'Download discovered files','robots':'Respect robots.txt','depth':'Maximum depth','file_size':'Maximum file size (bytes)','total_size':'Maximum total download (bytes)','types':'File types','workers':'Workers','rate':'Requests / second / host','retries':'Retries','archive':'Internet Archive','local':'Local PC folder','both':'Both destinations','folder':'Folder','pages':'Pages scanned','found':'Files found','downloaded':'Downloaded','errors':'Errors','queue':'Queue','speed':'Speed','custom':'Custom language','language':'Language','editor':'Language editor'},
'hy': {'title':'AWEC Desktop','dashboard':'Կառավարման վահանակ','crawler':'Սքանավորող','storage':'Պահպանում','languages':'Լեզուներ','settings':'Կարգավորումներ','running':'AWEC Աշխատում է','stopped':'AWEC Կանգնած է','start':'Սկսել','pause':'Դադար','stop':'Կանգնեցնել','resume':'Շարունակել','add':'Ավելացնել','remove':'Հեռացնել','import':'Ներմուծել','browse':'Ընտրել','save':'Պահպանել','apply':'Կիրառել','seed':'Սկզբնական հղումներ','follow':'Հետևել հղումներին','sub':'Հետևել ենթադոմեյններին','external':'Հետևել արտաքին դոմեյններին','files':'Ներբեռնել գտնված ֆայլերը','robots':'Հարգել robots.txt','depth':'Առավելագույն խորություն','file_size':'Առանձին ֆայլի առավելագույն չափ (բայթ)','total_size':'Ընդհանուր ներբեռնման առավելագույն չափ (բայթ)','types':'Ֆայլերի տեսակներ','workers':'Գործողություններ','rate':'Հարցումներ / վրկ / հոսթ','retries':'Կրկնակի փորձեր','archive':'Internet Archive','local':'Համակարգչի պանակ','both':'Երկու ուղղությամբ','folder':'Պանակ','pages':'Սքանավորված էջեր','found':'Գտնված ֆայլեր','downloaded':'Ներբեռնված','errors':'Սխալներ','queue':'Հերթ','speed':'Արագություն','custom':'Custom լեզու','language':'Լեզու','editor':'Լեզվի խմբագրիչ'},
'ru': {'title':'AWEC Desktop','dashboard':'Панель','crawler':'Сканер','storage':'Хранилище','languages':'Языки','settings':'Настройки','running':'AWEC работает','stopped':'AWEC остановлен','start':'Запуск','pause':'Пауза','stop':'Стоп','resume':'Продолжить','add':'Добавить','remove':'Удалить','import':'Импорт','browse':'Обзор','save':'Сохранить','apply':'Применить','seed':'Начальные URL','follow':'Следовать ссылкам','sub':'Следовать поддоменам','external':'Внешние домены','files':'Загружать найденные файлы','robots':'Соблюдать robots.txt','depth':'Максимальная глубина','file_size':'Макс. размер файла (байт)','total_size':'Макс. общий объём (байт)','types':'Типы файлов','workers':'Рабочие','rate':'Запросов / сек / хост','retries':'Повторы','archive':'Internet Archive','local':'Папка ПК','both':'Оба назначения','folder':'Папка','pages':'Страниц','found':'Файлов найдено','downloaded':'Загружено','errors':'Ошибки','queue':'Очередь','speed':'Скорость','custom':'Пользовательский язык','language':'Язык','editor':'Редактор языка'},
'es': {'title':'AWEC Desktop','dashboard':'Panel','crawler':'Crawler','storage':'Almacenamiento','languages':'Idiomas','settings':'Ajustes','running':'AWEC en ejecución','stopped':'AWEC detenido','start':'Iniciar','pause':'Pausa','stop':'Detener','resume':'Continuar','add':'Añadir','remove':'Eliminar','import':'Importar','browse':'Examinar','save':'Guardar','apply':'Aplicar','seed':'URLs iniciales','follow':'Seguir enlaces','sub':'Seguir subdominios','external':'Dominios externos','files':'Descargar archivos encontrados','robots':'Respetar robots.txt','depth':'Profundidad máxima','file_size':'Tamaño máximo de archivo (bytes)','total_size':'Descarga total máxima (bytes)','types':'Tipos de archivo','workers':'Trabajadores','rate':'Solicitudes / seg / host','retries':'Reintentos','archive':'Internet Archive','local':'Carpeta local','both':'Ambos destinos','folder':'Carpeta','pages':'Páginas','found':'Archivos encontrados','downloaded':'Descargado','errors':'Errores','queue':'Cola','speed':'Velocidad','custom':'Idioma personalizado','language':'Idioma','editor':'Editor de idioma'},
'fr': {'title':'AWEC Desktop','dashboard':'Tableau de bord','crawler':'Crawler','storage':'Stockage','languages':'Langues','settings':'Paramètres','running':'AWEC en cours','stopped':'AWEC arrêté','start':'Démarrer','pause':'Pause','stop':'Arrêter','resume':'Reprendre','add':'Ajouter','remove':'Supprimer','import':'Importer','browse':'Parcourir','save':'Enregistrer','apply':'Appliquer','seed':'URLs de départ','follow':'Suivre les liens','sub':'Suivre les sous-domaines','external':'Domaines externes','files':'Télécharger les fichiers trouvés','robots':'Respecter robots.txt','depth':'Profondeur maximale','file_size':'Taille maximale du fichier (octets)','total_size':'Téléchargement total maximal (octets)','types':'Types de fichiers','workers':'Travailleurs','rate':'Requêtes / sec / hôte','retries':'Tentatives','archive':'Internet Archive','local':'Dossier local','both':'Deux destinations','folder':'Dossier','pages':'Pages analysées','found':'Fichiers trouvés','downloaded':'Téléchargé','errors':'Erreurs','queue':'File','speed':'Vitesse','custom':'Langue personnalisée','language':'Langue','editor':'Éditeur de langue'},
'de': {'title':'AWEC Desktop','dashboard':'Dashboard','crawler':'Crawler','storage':'Speicher','languages':'Sprachen','settings':'Einstellungen','running':'AWEC läuft','stopped':'AWEC gestoppt','start':'Start','pause':'Pause','stop':'Stop','resume':'Fortsetzen','add':'Hinzufügen','remove':'Entfernen','import':'Importieren','browse':'Durchsuchen','save':'Speichern','apply':'Anwenden','seed':'Start-URLs','follow':'Links folgen','sub':'Subdomains folgen','external':'Externe Domains','files':'Gefundene Dateien laden','robots':'robots.txt beachten','depth':'Maximale Tiefe','file_size':'Maximale Dateigröße (Bytes)','total_size':'Maximaler Gesamtdownload (Bytes)','types':'Dateitypen','workers':'Worker','rate':'Anfragen / Sek. / Host','retries':'Wiederholungen','archive':'Internet Archive','local':'Lokaler PC-Ordner','both':'Beide Ziele','folder':'Ordner','pages':'Seiten','found':'Gefundene Dateien','downloaded':'Heruntergeladen','errors':'Fehler','queue':'Warteschlange','speed':'Geschwindigkeit','custom':'Benutzerdefinierte Sprache','language':'Sprache','editor':'Sprachen-Editor'},
'pt': {'title':'AWEC Desktop','dashboard':'Painel','crawler':'Crawler','storage':'Armazenamento','languages':'Idiomas','settings':'Definições','running':'AWEC em execução','stopped':'AWEC parado','start':'Iniciar','pause':'Pausa','stop':'Parar','resume':'Retomar','add':'Adicionar','remove':'Remover','import':'Importar','browse':'Procurar','save':'Guardar','apply':'Aplicar','seed':'URLs iniciais','follow':'Seguir ligações','sub':'Seguir subdomínios','external':'Domínios externos','files':'Descarregar ficheiros encontrados','robots':'Respeitar robots.txt','depth':'Profundidade máxima','file_size':'Tamanho máximo do ficheiro (bytes)','total_size':'Download total máximo (bytes)','types':'Tipos de ficheiro','workers':'Workers','rate':'Pedidos / seg / host','retries':'Tentativas','archive':'Internet Archive','local':'Pasta local','both':'Ambos os destinos','folder':'Pasta','pages':'Páginas','found':'Ficheiros encontrados','downloaded':'Descarregado','errors':'Erros','queue':'Fila','speed':'Velocidade','custom':'Idioma personalizado','language':'Idioma','editor':'Editor de idioma'},
'it': {'title':'AWEC Desktop','dashboard':'Dashboard','crawler':'Crawler','storage':'Archiviazione','languages':'Lingue','settings':'Impostazioni','running':'AWEC in esecuzione','stopped':'AWEC fermo','start':'Avvia','pause':'Pausa','stop':'Ferma','resume':'Riprendi','add':'Aggiungi','remove':'Rimuovi','import':'Importa','browse':'Sfoglia','save':'Salva','apply':'Applica','seed':'URL iniziali','follow':'Segui link','sub':'Segui sottodomini','external':'Domini esterni','files':'Scarica file trovati','robots':'Rispetta robots.txt','depth':'Profondità massima','file_size':'Dimensione massima file (byte)','total_size':'Download totale massimo (byte)','types':'Tipi di file','workers':'Worker','rate':'Richieste / sec / host','retries':'Tentativi','archive':'Internet Archive','local':'Cartella PC','both':'Entrambe le destinazioni','folder':'Cartella','pages':'Pagine','found':'File trovati','downloaded':'Scaricati','errors':'Errori','queue':'Coda','speed':'Velocità','custom':'Lingua personalizzata','language':'Lingua','editor':'Editor lingua'},
'zh': {'title':'AWEC Desktop','dashboard':'仪表盘','crawler':'爬虫','storage':'存储','languages':'语言','settings':'设置','running':'AWEC 正在运行','stopped':'AWEC 已停止','start':'开始','pause':'暂停','stop':'停止','resume':'继续','add':'添加','remove':'删除','import':'导入','browse':'浏览','save':'保存','apply':'应用','seed':'种子 URL','follow':'跟踪链接','sub':'跟踪子域名','external':'外部域名','files':'下载发现的文件','robots':'遵守 robots.txt','depth':'最大深度','file_size':'最大文件大小（字节）','total_size':'最大总下载量（字节）','types':'文件类型','workers':'工作线程','rate':'每主机请求/秒','retries':'重试次数','archive':'Internet Archive','local':'本地文件夹','both':'两个目标','folder':'文件夹','pages':'已扫描页面','found':'发现文件','downloaded':'已下载','errors':'错误','queue':'队列','speed':'速度','custom':'自定义语言','language':'语言','editor':'语言编辑器'},
'ja': {'title':'AWEC Desktop','dashboard':'ダッシュボード','crawler':'クローラー','storage':'ストレージ','languages':'言語','settings':'設定','running':'AWEC 実行中','stopped':'AWEC 停止','start':'開始','pause':'一時停止','stop':'停止','resume':'再開','add':'追加','remove':'削除','import':'インポート','browse':'参照','save':'保存','apply':'適用','seed':'シード URL','follow':'リンクを追跡','sub':'サブドメインを追跡','external':'外部ドメイン','files':'発見したファイルをダウンロード','robots':'robots.txt を尊重','depth':'最大深度','file_size':'最大ファイルサイズ（バイト）','total_size':'最大総ダウンロード（バイト）','types':'ファイル形式','workers':'ワーカー','rate':'ホスト毎のリクエスト/秒','retries':'再試行','archive':'Internet Archive','local':'ローカルフォルダー','both':'両方の保存先','folder':'フォルダー','pages':'スキャン済みページ','found':'発見ファイル','downloaded':'ダウンロード済み','errors':'エラー','queue':'キュー','speed':'速度','custom':'カスタム言語','language':'言語','editor':'言語エディター'}
}

class AWECMainWindow(QMainWindow):
    def __init__(self):
        super().__init__(); self.lang='en'; self.running=False; self.cfg=AWECConfig(); self.setMinimumSize(1180,760); self._build(); self.retranslate()
    def _build(self):
        root=QWidget(); self.setCentralWidget(root); outer=QHBoxLayout(root); outer.setContentsMargins(0,0,0,0)
        self.side=QFrame(); self.side.setObjectName('sidebar'); sl=QVBoxLayout(self.side); sl.setContentsMargins(18,24,18,18)
        self.logo=QLabel('AWEC'); self.logo.setObjectName('logo'); sl.addWidget(self.logo); self.nav=[]
        for i in range(5):
            b=QPushButton(); b.setCheckable(True); b.clicked.connect(lambda _,x=i:self.pages.setCurrentIndex(x)); sl.addWidget(b); self.nav.append(b)
        sl.addStretch(); self.version=QLabel('AWEC Desktop • v1'); sl.addWidget(self.version); outer.addWidget(self.side,0)
        self.pages=QStackedWidget(); outer.addWidget(self.pages,1)
        self._dashboard(); self._crawler(); self._storage(); self._languages(); self._settings()
    def _page(self,title):
        w=QWidget(); l=QVBoxLayout(w); l.setContentsMargins(30,28,30,28); h=QLabel(title); h.setObjectName('pageTitle'); l.addWidget(h); return w,l,h
    def _dashboard(self):
        w,l,self.dtitle=self._page('Dashboard'); grid=QGridLayout(); self.metrics={}
        for i,k in enumerate(['pages','found','downloaded','errors','queue','speed']):
            f=QFrame(); f.setObjectName('card'); q=QVBoxLayout(f); a=QLabel(); a.setObjectName('metric'); b=QLabel(); q.addWidget(a); q.addWidget(b); self.metrics[k]=(a,b); grid.addWidget(f,i//3,i%3)
        l.addLayout(grid); self.progress=QProgressBar(); self.progress.setValue(0); l.addWidget(self.progress); self.live=QTextEdit(); self.live.setReadOnly(True); l.addWidget(self.live); self.pages.addWidget(w)
    def _crawler(self):
        w,l,self.ctitle=self._page('Crawler'); form=QFormLayout(); self.seed=QLineEdit(); self.seed.setPlaceholderText('https://example.com/'); form.addRow('Seed URL',self.seed); self.depth=QSpinBox(); self.depth.setRange(-1,100); self.depth.setValue(3); form.addRow('Depth',self.depth); self.maxfile=QLineEdit('-1'); self.total=QLineEdit(str(10*1024**3)); form.addRow('Max file',self.maxfile); form.addRow('Max total',self.total); self.types=QLineEdit('*'); form.addRow('Types',self.types); self.workers=QSpinBox(); self.workers.setRange(1,128); self.workers.setValue(16); form.addRow('Workers',self.workers); self.rate=QDoubleSpinBox(); self.rate.setRange(.1,100); self.rate.setValue(2); form.addRow('Rate',self.rate); l.addLayout(form)
        self.checks=[]
        for key,val in [('follow',True),('sub',True),('external',False),('files',True),('robots',True)]: c=QCheckBox(); c.setChecked(val); l.addWidget(c); self.checks.append((key,c))
        row=QHBoxLayout(); self.add=QPushButton(); self.add.clicked.connect(lambda:self.live.append(self.seed.text())); self.start=QPushButton(); self.start.clicked.connect(self.toggle_start); self.pause=QPushButton(); self.stop=QPushButton(); self.stop.clicked.connect(self.stop_run); self.imp=QPushButton(); self.imp.clicked.connect(self.import_seeds); [row.addWidget(x) for x in [self.add,self.imp,self.start,self.pause,self.stop]]; l.addLayout(row); l.addStretch(); self.pages.addWidget(w)
    def _storage(self):
        w,l,self.stitle=self._page('Storage'); self.dest=QComboBox(); self.dest.addItems(['Internet Archive','Local PC folder','Both destinations']); l.addWidget(self.dest); self.folder=QLineEdit(); br=QPushButton(); br.clicked.connect(self.pick_folder); r=QHBoxLayout(); r.addWidget(self.folder); r.addWidget(br); l.addLayout(r); self.item=QLineEdit('domain-DD-MM-YYYY-awec'); l.addWidget(self.item); l.addStretch(); self.pages.addWidget(w)
    def _languages(self):
        w,l,self.ltitle=self._page('Languages'); self.langbox=QComboBox(); self.langbox.addItems(['English','Հայերեն','Русский','Español','Français','Deutsch','Português','Italiano','中文','日本語']); self.langbox.currentIndexChanged.connect(self.change_language); l.addWidget(self.langbox); self.custom=QPushButton(); self.custom.clicked.connect(self.load_custom); l.addWidget(self.custom); self.editor=QTextEdit(); self.editor.setPlaceholderText('key=value'); l.addWidget(self.editor); self.save_lang=QPushButton(); self.save_lang.clicked.connect(self.save_custom); l.addWidget(self.save_lang); self.pages.addWidget(w)
    def _settings(self):
        w,l,self.settitle=self._page('Settings'); self.theme=QComboBox(); self.theme.addItems(['Dark','Light']); l.addWidget(self.theme); l.addWidget(QLabel('All crawler configuration is persisted through AWECConfig.')); self.pages.addWidget(w)
    def change_language(self,i):
        self.lang=['en','hy','ru','es','fr','de','pt','it','zh','ja'][i]; self.retranslate()
    def t(self,k): return BASE.get(self.lang,BASE['en']).get(k,k)
    def retranslate(self):
        self.setWindowTitle(self.t('title')); names=['dashboard','crawler','storage','languages','settings'];
        for b,k in zip(self.nav,names): b.setText(self.t(k))
        for obj,key in [(self.dtitle,'dashboard'),(self.ctitle,'crawler'),(self.stitle,'storage'),(self.ltitle,'languages'),(self.settitle,'settings')]: obj.setText(self.t(key))
        for k,(a,b) in self.metrics.items(): a.setText(self.t(k)); b.setText('0')
        for key,c in self.checks: c.setText(self.t(key))
        self.add.setText(self.t('add')); self.imp.setText(self.t('import')); self.start.setText(self.t('start')); self.pause.setText(self.t('pause')); self.stop.setText(self.t('stop')); self.custom.setText(self.t('custom')); self.save_lang.setText(self.t('save'))
    def toggle_start(self): self.running=True; self.start.setText(self.t('pause')); self.live.append(self.t('running')); self.progress.setValue(1)
    def stop_run(self): self.running=False; self.start.setText(self.t('start')); self.live.append(self.t('stopped'))
    def import_seeds(self):
        p,_=QFileDialog.getOpenFileName(self,'Import','', 'Seeds (*.txt *.json *.docx)');
        if p: self.live.append(f'Imported: {p}')
    def pick_folder(self): self.folder.setText(QFileDialog.getExistingDirectory(self,'Folder'))
    def load_custom(self):
        p,_=QFileDialog.getOpenFileName(self,'Custom language','', 'AWEC language (*.awec.language)');
        if p: self.editor.setPlainText(Path(p).read_text(encoding='utf-8'))
    def save_custom(self):
        p,_=QFileDialog.getSaveFileName(self,'Save language','custom.awec.language','AWEC language (*.awec.language)');
        if p: Path(p).write_text(self.editor.toPlainText(),encoding='utf-8')
